// Word data for Year 4 (Australian Curriculum) English Vocabulary Practice
// Definitions and examples are written at a Year 4 (age 9-10) reading level.

const WORD_BANK = {
  vocabulary: [
    { word: "ancient", definition: "Very old, from a long time ago.", example: "The museum has an ancient Egyptian statue." },
    { word: "enormous", definition: "Extremely large in size.", example: "A blue whale is an enormous animal." },
    { word: "fragile", definition: "Easily broken or damaged.", example: "Please carry the fragile glass carefully." },
    { word: "curious", definition: "Eager to know or learn something.", example: "The curious student asked lots of questions." },
    { word: "delicate", definition: "Easily damaged; fine and light.", example: "Butterfly wings are very delicate." },
    { word: "vanish", definition: "To disappear suddenly.", example: "The magician made the coin vanish." },
    { word: "glimpse", definition: "A very brief or quick look.", example: "We caught a glimpse of the koala in the tree." },
    { word: "explore", definition: "To travel and look around a new place to learn about it.", example: "We will explore the rainforest on our excursion." },
    { word: "habitat", definition: "The natural home of an animal or plant.", example: "The wetland is a habitat for many birds." },
    { word: "migrate", definition: "To move from one place to another, often with the seasons.", example: "Humpback whales migrate along the coast each year." },
    { word: "nocturnal", definition: "Active at night rather than during the day.", example: "The possum is a nocturnal animal." },
    { word: "predator", definition: "An animal that hunts other animals for food.", example: "A dingo is a predator in the outback." },
    { word: "survive", definition: "To stay alive, especially in a difficult situation.", example: "Camels can survive without water for a long time." },
    { word: "drought", definition: "A long period of very little or no rain.", example: "The farmers hoped the drought would end soon." },
    { word: "erosion", definition: "The wearing away of land by wind, water or ice.", example: "Erosion has shaped the cliffs along the coast." },
    { word: "temperature", definition: "How hot or cold something is.", example: "The temperature dropped at night in the desert." },
    { word: "container", definition: "Something used to hold or store things.", example: "She packed her lunch in a plastic container." },
    { word: "vehicle", definition: "A machine used to carry people or goods, such as a car or truck.", example: "A bicycle is a simple kind of vehicle." },
    { word: "structure", definition: "The way something is built or put together.", example: "The bridge has a strong steel structure." },
    { word: "material", definition: "The substance that something is made from.", example: "Wool is a warm material used to make jumpers." },
    { word: "device", definition: "A tool or machine made for a special purpose.", example: "A thermometer is a device that measures temperature." },
    { word: "invention", definition: "Something that has been designed and made for the first time.", example: "The telephone was an amazing invention." },
    { word: "energy", definition: "The power needed to do work or make things happen.", example: "Solar panels turn sunlight into energy." },
    { word: "resource", definition: "Something that is useful or valuable, like water or timber.", example: "Fresh water is an important resource." },
    { word: "environment", definition: "The natural world around us, including land, air and water.", example: "We should look after our environment." },
    { word: "pollution", definition: "Harmful or dirty substances that damage air, water or land.", example: "Plastic in the ocean causes pollution." },
    { word: "recycle", definition: "To use waste material again instead of throwing it away.", example: "We recycle paper, glass and plastic at school." },
    { word: "community", definition: "A group of people living in the same area.", example: "Our community held a fete to raise money." },
    { word: "culture", definition: "The customs, beliefs and way of life of a group of people.", example: "Aboriginal culture is the oldest living culture in the world." },
    { word: "tradition", definition: "A custom or belief passed down from one generation to the next.", example: "Sharing a meal together is a family tradition." },
    { word: "celebration", definition: "A special event to mark a happy occasion.", example: "The party was a celebration of her birthday." },
    { word: "ceremony", definition: "A formal event held for a special reason.", example: "We attended the ANZAC Day ceremony." },
    { word: "continent", definition: "One of the seven large land areas of the Earth.", example: "Australia is the smallest continent." },
    { word: "territory", definition: "An area of land, especially one controlled by a government.", example: "The Northern Territory is in the centre of Australia." },
    { word: "landmark", definition: "A famous or easily recognised place or building.", example: "The Sydney Opera House is a famous landmark." },
    { word: "expedition", definition: "A journey made for a particular purpose, such as exploring.", example: "The scientists went on an expedition to Antarctica." },
    { word: "navigate", definition: "To find your way from one place to another.", example: "Sailors used the stars to navigate the ocean." },
    { word: "compass", definition: "A tool that shows direction, always pointing north.", example: "We used a compass to find our way through the bush." },
    { word: "boundary", definition: "A line that marks the edge or limit of an area.", example: "The fence marks the boundary of the farm." },
    { word: "region", definition: "An area of a country or the world with its own features.", example: "The Kimberley is a remote region of Western Australia." },
    { word: "opinion", definition: "A belief or view about something that is not a fact.", example: "In my opinion, the book was better than the film." },
    { word: "evidence", definition: "Facts or information that show something is true.", example: "The detective looked for evidence at the scene." },
    { word: "conclude", definition: "To decide something after thinking about the facts.", example: "We can conclude that the plant needs sunlight to grow." },
    { word: "predict", definition: "To say what you think will happen in the future.", example: "Can you predict what will happen next in the story?" },
    { word: "compare", definition: "To look at two or more things to find what is similar or different.", example: "Let's compare the size of these two leaves." },
    { word: "contrast", definition: "To show how two things are different.", example: "The bright colours contrast with the dark background." },
    { word: "summarise", definition: "To give the main points of something in a few words.", example: "Please summarise the story in three sentences." },
    { word: "identify", definition: "To recognise and correctly name something.", example: "Can you identify the bird in this picture?" },
    { word: "investigate", definition: "To carefully look into something to find out more.", example: "The scientists will investigate the strange rock." },
    { word: "observe", definition: "To watch something carefully.", example: "We observed the ants building their nest." },
    { word: "diagram", definition: "A drawing that explains or shows how something works.", example: "The diagram shows the parts of a plant." },
    { word: "sequence", definition: "The order in which things happen.", example: "Put the events of the story in the correct sequence." },
    { word: "narrator", definition: "The person who tells the story.", example: "The narrator described the forest in great detail." },
    { word: "character", definition: "A person or animal in a story.", example: "The main character in the book is a brave girl." },
    { word: "setting", definition: "The time and place where a story happens.", example: "The setting of the story is a small country town." },
    { word: "dialogue", definition: "Conversation written between characters in a story.", example: "The dialogue between the two friends was funny." },
    { word: "paragraph", definition: "A group of sentences about one main idea.", example: "Each paragraph in your report should have a topic sentence." },
    { word: "punctuation", definition: "Marks like full stops and commas used in writing.", example: "Remember to use correct punctuation in your sentences." },
    { word: "vocabulary", definition: "The words a person knows and uses.", example: "Reading helps you build a bigger vocabulary." },
    { word: "definition", definition: "An explanation of what a word means.", example: "Look up the definition of the word in the dictionary." },
    { word: "generous", definition: "Willing to give and share freely.", example: "It was generous of her to share her lunch." },
    { word: "honest", definition: "Truthful and not likely to lie, cheat or steal.", example: "It's important to be honest with your friends." },
    { word: "responsible", definition: "Able to be trusted to do the right thing.", example: "A responsible pet owner feeds their dog every day." },
    { word: "confident", definition: "Feeling sure about your own abilities.", example: "She felt confident before her speech." },
    { word: "anxious", definition: "Feeling worried or nervous about something.", example: "He was anxious about his first day at a new school." },
    { word: "furious", definition: "Extremely angry.", example: "Dad was furious when the vase broke." },
    { word: "exhausted", definition: "Extremely tired.", example: "After the long hike, we were exhausted." },
    { word: "astonished", definition: "Very surprised.", example: "We were astonished by the size of the whale." },
    { word: "reluctant", definition: "Not willing to do something.", example: "The reluctant puppy did not want to go outside in the rain." },
    { word: "cautious", definition: "Careful to avoid danger or mistakes.", example: "Be cautious when crossing a busy road." },
  ],

  spelling: [
    { word: "believe", tip: "Remember: i before e, except after c." },
    { word: "because", tip: "Think: Big Elephants Can Always Understand Small Elephants." },
    { word: "beautiful", tip: "'Beauty' + 'ful' — remember the 'eau'." },
    { word: "different", tip: "Two syllables can hide: dif-fer-ent." },
    { word: "favourite", tip: "Australian spelling keeps the 'u' — favour + ite." },
    { word: "separate", tip: "There's 'a rat' in sep-a-rate." },
    { word: "definitely", tip: "There's 'finite' hidden inside definitely." },
    { word: "necessary", tip: "One collar, two sleeves: 1 'c', 2 's's." },
    { word: "surprise", tip: "Don't forget the silent 'r' — sur-prise." },
    { word: "language", tip: "Lang + u + age, not 'languege'." },
    { word: "February", tip: "Don't forget the first 'r' — Feb-ru-ary." },
    { word: "Wednesday", tip: "Wed-nes-day — the 'd' is silent." },
    { word: "although", tip: "'Al' + 'though' — say each part slowly." },
    { word: "thorough", tip: "Th-orough, not 'thor-ow'." },
    { word: "government", tip: "Don't forget the 'n' before 'ment' — govern + ment." },
    { word: "environment", tip: "Don't forget the 'n' — environ + ment." },
    { word: "immediately", tip: "Double 'm' — im + mediately." },
    { word: "occasion", tip: "Double 'c', single 's' — oc-ca-sion." },
    { word: "recommend", tip: "One 'c', double 'm' — re-com-mend." },
    { word: "disappear", tip: "Double 's', single 'p' — dis-ap-pear." },
    { word: "disappoint", tip: "Double 's', double 'p' — dis-ap-point." },
    { word: "embarrass", tip: "Double 'r', double 's' — em-bar-rass." },
    { word: "excellent", tip: "Double 'l' — ex-cel-lent." },
    { word: "opposite", tip: "Double 'p' — op-po-site." },
    { word: "possible", tip: "Double 's' — pos-si-ble." },
    { word: "address", tip: "Double 'd', double 's' — ad-dress." },
    { word: "achieve", tip: "i before e, except after c — a-chieve." },
    { word: "receive", tip: "i before e, except after c — re-ceive." },
    { word: "friend", tip: "'Fri' + 'end' — a friend to the end." },
    { word: "knowledge", tip: "Silent 'k' — know + ledge." },
    { word: "island", tip: "Silent 's' — i-s-land." },
    { word: "answer", tip: "Silent 'w' — an-s-wer." },
    { word: "listen", tip: "Silent 't' — lis-ten." },
    { word: "straight", tip: "Str + aigh + t — think of a straight line." },
    { word: "though", tip: "T-h-o-u-g-h — not pronounced how it looks." },
    { word: "through", tip: "Th-r-ough, like 'threw' but spelt differently." },
    { word: "guard", tip: "Silent 'u' — g-u-a-r-d." },
    { word: "guide", tip: "Silent 'u' — g-u-i-d-e." },
    { word: "vegetable", tip: "Don't forget the middle 'e' — veg-e-table." },
    { word: "interesting", tip: "In-ter-est-ing — five syllables, don't skip any." },
    { word: "library", tip: "Two 'r's hiding — lib-r-a-r-y." },
    { word: "probably", tip: "Prob-ab-ly — don't drop the middle 'a'." },
    { word: "actually", tip: "Act + u + ally, not 'actully'." },
    { word: "especially", tip: "E-special-ly — 'special' is hidden inside." },
    { word: "experience", tip: "Ex-peri-ence — say each part slowly." },
    { word: "restaurant", tip: "Rest + au + rant — tricky French spelling." },
    { word: "neighbour", tip: "Silent 'gh' — neigh + bour." },
    { word: "height", tip: "H-e-i-g-h-t, rhymes with 'kite'." },
    { word: "weight", tip: "W-e-i-g-h-t, rhymes with 'gate'." },
  ],

  synonyms: [
    { word: "happy", synonym: "joyful", antonym: "sad" },
    { word: "big", synonym: "enormous", antonym: "tiny" },
    { word: "small", synonym: "little", antonym: "huge" },
    { word: "fast", synonym: "quick", antonym: "slow" },
    { word: "brave", synonym: "courageous", antonym: "cowardly" },
    { word: "smart", synonym: "clever", antonym: "foolish" },
    { word: "angry", synonym: "furious", antonym: "calm" },
    { word: "quiet", synonym: "silent", antonym: "loud" },
    { word: "old", synonym: "ancient", antonym: "modern" },
    { word: "beautiful", synonym: "gorgeous", antonym: "ugly" },
    { word: "difficult", synonym: "challenging", antonym: "easy" },
    { word: "begin", synonym: "start", antonym: "finish" },
    { word: "tired", synonym: "exhausted", antonym: "energetic" },
    { word: "funny", synonym: "hilarious", antonym: "serious" },
    { word: "strong", synonym: "powerful", antonym: "weak" },
    { word: "generous", synonym: "kind", antonym: "selfish" },
    { word: "true", synonym: "honest", antonym: "false" },
    { word: "empty", synonym: "vacant", antonym: "full" },
    { word: "ancient", synonym: "old", antonym: "modern" },
    { word: "gigantic", synonym: "huge", antonym: "minuscule" },
    { word: "bright", synonym: "shiny", antonym: "dull" },
    { word: "polite", synonym: "courteous", antonym: "rude" },
    { word: "brief", synonym: "short", antonym: "lengthy" },
    { word: "curious", synonym: "inquisitive", antonym: "indifferent" },
    { word: "gloomy", synonym: "dark", antonym: "cheerful" },
    { word: "fragile", synonym: "delicate", antonym: "sturdy" },
    { word: "rapid", synonym: "swift", antonym: "sluggish" },
    { word: "vast", synonym: "enormous", antonym: "tiny" },
    { word: "ancient ruins", synonym: "old structures", antonym: "new buildings" },
    { word: "cautious", synonym: "careful", antonym: "reckless" },
  ],

  homophones: [
    { pair: ["their", "there"], defs: ["belonging to them", "in that place"] },
    { pair: ["there", "they're"], defs: ["in that place", "they are"] },
    { pair: ["to", "too"], defs: ["towards", "also / excessively"] },
    { pair: ["your", "you're"], defs: ["belonging to you", "you are"] },
    { pair: ["its", "it's"], defs: ["belonging to it", "it is / it has"] },
    { pair: ["whose", "who's"], defs: ["belonging to whom", "who is / who has"] },
    { pair: ["here", "hear"], defs: ["in this place", "to listen with your ears"] },
    { pair: ["write", "right"], defs: ["to put words on paper", "correct, or a direction"] },
    { pair: ["knew", "new"], defs: ["past tense of know", "not old"] },
    { pair: ["know", "no"], defs: ["to understand something", "not any / opposite of yes"] },
    { pair: ["sea", "see"], defs: ["a large body of salt water", "to look with your eyes"] },
    { pair: ["sun", "son"], defs: ["the star at the centre of our solar system", "a male child"] },
    { pair: ["flower", "flour"], defs: ["the bloom of a plant", "a powder used for baking"] },
    { pair: ["hour", "our"], defs: ["a unit of time (60 minutes)", "belonging to us"] },
    { pair: ["meat", "meet"], defs: ["food from an animal", "to come together with someone"] },
    { pair: ["piece", "peace"], defs: ["a part of something", "calm, without war"] },
    { pair: ["break", "brake"], defs: ["to smash or split", "used to stop a vehicle"] },
    { pair: ["weather", "whether"], defs: ["the conditions outside, like rain or sun", "used to show a choice between options"] },
    { pair: ["ate", "eight"], defs: ["past tense of eat", "the number 8"] },
    { pair: ["blue", "blew"], defs: ["a colour", "past tense of blow"] },
  ],
};
