-- Shared word list. A word with owner_id NULL was added by an admin and is
-- visible to everyone (including signed-out visitors); a word with owner_id
-- set belongs to that one paid user and is visible only to them.
CREATE TABLE IF NOT EXISTS shared_words (
  id TEXT PRIMARY KEY,
  word TEXT NOT NULL,
  definition_en TEXT,
  definition_ko TEXT,
  level_en TEXT,
  level_ko TEXT,
  example TEXT NOT NULL DEFAULT '',
  no_definition_en INTEGER NOT NULL DEFAULT 0,
  no_definition_ko INTEGER NOT NULL DEFAULT 0,
  source TEXT,
  owner_id TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_shared_words_word ON shared_words (word);
CREATE INDEX IF NOT EXISTS idx_shared_words_owner ON shared_words (owner_id);

-- User accounts. Passwords are stored as a PBKDF2-SHA256 hash with a random
-- per-user salt — never in plaintext, never reversible. role is one of
-- 'admin' | 'paid' | 'free'. upgraded_at is set whenever role transitions to
-- 'paid' (signup with a code, self-serve upgrade, or an admin setting the
-- role directly) and left alone on any other role change, so it always
-- reads as "the last time this account became paid".
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'free',
  created_at INTEGER NOT NULL,
  upgraded_at INTEGER
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);

-- Special codes: single-use, generated by an admin and redeemed at signup (or
-- via an existing free account's upgrade) to grant the 'paid' role instead of
-- the default 'free' one. Stands in for a payment system that doesn't exist
-- yet — redeemed_by/redeemed_at are set the moment a code is used, and a
-- redeemed code can never be reused. target_user_id, when set, means the code
-- was generated to fulfil a specific free account's upgrade request — only
-- that account may redeem it (and only through the upgrade endpoint, never
-- at signup, since it presumes an account that already exists).
CREATE TABLE IF NOT EXISTS special_codes (
  code TEXT PRIMARY KEY,
  created_by TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  redeemed_by TEXT,
  redeemed_at INTEGER,
  target_user_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_special_codes_redeemed_by ON special_codes (redeemed_by);
CREATE INDEX IF NOT EXISTS idx_special_codes_target ON special_codes (target_user_id);

-- A free account's request to be upgraded to paid. An admin reviews pending
-- requests and, on approval, generates a special code targeted at that one
-- user (see target_user_id above) — the code then sits on the request row so
-- the requester can see it arrived and redeem it themselves.
CREATE TABLE IF NOT EXISTS upgrade_requests (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending' | 'fulfilled' | 'dismissed'
  requested_at INTEGER NOT NULL,
  fulfilled_at INTEGER,
  code TEXT
);

CREATE INDEX IF NOT EXISTS idx_upgrade_requests_user ON upgrade_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_upgrade_requests_status ON upgrade_requests (status);
