-- Shared word list. A word with owner_id NULL was added by an admin and is
-- visible to everyone (including signed-out visitors); a word with owner_id
-- set belongs to that one paid user and is visible only to them.
CREATE TABLE IF NOT EXISTS shared_words (
  id TEXT PRIMARY KEY,
  word TEXT NOT NULL,
  definition_en TEXT,
  definition_ko TEXT,
  level_en TEXT,
  level_ko TEXT,
  example TEXT NOT NULL DEFAULT '',
  no_definition_en INTEGER NOT NULL DEFAULT 0,
  no_definition_ko INTEGER NOT NULL DEFAULT 0,
  source TEXT,
  owner_id TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_shared_words_word ON shared_words (word);
CREATE INDEX IF NOT EXISTS idx_shared_words_owner ON shared_words (owner_id);

-- User accounts. Passwords are stored as a PBKDF2-SHA256 hash with a random
-- per-user salt — never in plaintext, never reversible. role is one of
-- 'admin' | 'paid' | 'free'.
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'free',
  created_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);

-- Special codes: single-use, generated by an admin and redeemed at signup to
-- grant the 'paid' role instead of the default 'free' one. Stands in for a
-- payment system that doesn't exist yet — redeemed_by/redeemed_at are set
-- the moment a code is used, and a redeemed code can never be reused.
CREATE TABLE IF NOT EXISTS special_codes (
  code TEXT PRIMARY KEY,
  created_by TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  redeemed_by TEXT,
  redeemed_at INTEGER
);

CREATE INDEX IF NOT EXISTS idx_special_codes_redeemed_by ON special_codes (redeemed_by);
